### ISSUE TITLE
elo

### ISSUE THREAD

**Issue by molendzik** [ZSAInfProject/PozaziemscyZaborcy#1]
JD

**Comment by Bravo555** [comment]
Co ty żeś właśnie kurwa powiedzioł o mje, ty mały ciulu? Wiydz, że żech skończył studja łoficerski jako jedyn z nojlepszych i byłech od razu potym wysłany na misje do Sosnowca i mom ponad trzista zabitych goroli na kuncie. Je żech wytrenowany w walce przeciwko gorylom i jeżech nojlepszym snajperym w calkij ślunskij armji. Nimażeś do mje niczym poza kolejnym lekim cylym. Zmiota cie z powierzchni Ziymi z precyzjom jakij byś nigdy nie przipuszczoł, zapamiyntosz moji słowa. Myślisz, że możesz se godać o mie co ci się podobo we internecie? No to pomyśl jeszcze roz, jebańcu. Już się kontaktuja z mojom tajnom sieciom szpiegów z całego Ślunska i twoji ajpi je namierzane, także lepij się przigotuj na lawina mułu. Tak cie przisypie, że abo od razu świtniesz, abo wyleziesz ale cie gorole dojadom za bycie czornym. W kożdym rozie, już możesz dzwonić do faroża, tak co ci jaki fajne miyjsce na kerhowje zajmie, synek. Już żeś je umrzitkiym. Moga być wszyndzi, w każdym momyncie, i moga cię zabić na ponad siedymset sposobów a to yno jak licza bez użycio żodnych narzyndzi. Nie yno żech je maksymalnie wytrenowany w walce bez broni, ale i mom dostymp do nojlepszych kilofów na colkim Ślunsku, ty mały giździe. Kiebyś yno wiedzioł co na siebie ściongniesz swoim "pierońsko śmiysznym" komyntarzym może byś się ugryz za wczasu w jynzyk. Ale żeś się nie ugryz, no ni? i tera zapłacisz za to cyna. Obsrom cie mojom wściekłościom i utopisz sie w jyj zalywie. Kurwa świtniesz, bajtlu.
