### ISSUE TITLE
The game randomly speeds up and down

### ISSUE THREAD

**Issue by Bravo555** [ZSAInfProject/PozaziemscyZaborcy#3]
The game randomly speeds up and down because it's running as fast as possible, since you don't limit the speed nor keep track of time since last update.
There are several approaches you can take when it comes to dealing with this. Of course it would be simplest to just limit game to 60FPS, but if you want, [here you can learn more about game loops and make it better](http://gameprogrammingpatterns.com/game-loop.html).

[**Pretty good job so far!**](https://www.youtube.com/watch?v=QgE-Y1rneog)

**Comment by KyattPL** [comment]
Probably done.

**Comment by Bravo555** [comment]
Tip: to close the issue via commit message you need to use one of the following [keywords](https://help.github.com/articles/closing-issues-using-keywords/).
